accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from . import views


app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accounts/login_form.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', views.UserCreateView.as_view(), name='signup'),

]

board/urls.py
from django.urls import path
from django.views.generic import ListView

from .views import question_views, answer_views
from .models import Question


app_name = 'board'

urlpatterns = [
    path('', question_views.question_list, name='index'),

    path('question/', question_views.question_create, name='question_create'),
    path('question/<int:question_id>/', question_views.question_detail, name='question_detail'),
    path('question/<int:question_id>/delete/', question_views.question_delete, name='question_delete'),
    path('question/<int:question_id>/update/', question_views.question_update, name='question_update'),

    path('question/<int:question_id>/answer/', answer_views.answer_create, name='answer_create'),
    path('answer/<int:answer_id>/delete', answer_views.answer_delete, name='answer_delete'),
    path('answer/<int:answer_id>/update', answer_views.answer_update, name='answer_update'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
    path('accounts/', include('accounts.urls')),

]

templates/base_delete_model.html
<!-- Button trigger modal -->
<button type="button" class="btn btn-outline-danger btn-sm" data-bs-toggle="modal" data-bs-target="#exampleModal">
    삭제
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">삭제 확인</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                삭제 하시겠습니까?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">취소</button>
                <form action="{{ link }}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger" >삭제</button>
                </form>
            </div>
        </div>
    </div>
</div>

templates/base_form.html
{% load django_bootstrap5 %}


<div class="container">
    <div class="d-flex justify-content-center mt-4">
        <div class="col-sm-4 ">
            <div class="card">
                <div class="card-header">
                    {{ form_name }}
                </div>
                <div class="card-body">
                    {% if form %}
                        <form action="" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% bootstrap_form form %}
                            <input class="btn btn-outline-success float-end" type="submit" value="{{ form_name }}">
                        </form>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <title>Site-Kwon</title>
</head>
<body>
<!-- Message Displaying Area -->
{% if messages %}
    {% for message in  messages %}
        {% if message.tags == 'error' %}
            <div class="alert alert-danger">{{ message }}</div>
        {% else %}
            <div class="alert alert-{{ message.tags }}">{{ message }}</div>
        {% endif %}
    {% endfor %}
{% endif %}

<!-- Navigation Bar -->
<div class="container">
    <div class="d-flex flex-column flex-md-row align-items-center pb-3 mt-4 mb-4 border-bottom">
        <a href="{% url 'board:index' %}"
           class="d-flex align-items-center text-dark text-decoration-none">
            <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="me-2" viewBox="0 0 118 94" role="img">
                <path fill-rule="evenodd" clip-rule="evenodd"
                      d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z"
                      fill="currentColor"></path>
            </svg>
            <span class="fs-4">Kwon's Board</span>
        </a>
        <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
            <div class="container">
            {% if user.is_authenticated %}
                <span>LOGIN USER : <strong>{{ user.username }}</strong></span>
                <a href="{% url 'accounts:logout' %}" class="btn btn-outline-secondary" role="button">Logout</a>
            {% else %}
                <a href="{% url 'accounts:signup' %}" class="btn btn-outline-secondary" role="button">Signup</a>
                <a href="{% url 'accounts:login' %}" class="btn btn-outline-dark" role="button">Login</a>
            {% endif %}
            </div>
        </nav>
    </div>
</div>

<!-- Page Body -->
{% block content %}
    Contents Block
{% endblock %}


<!-- Footer -->
<div class="container mt-4">
    <div class="border-top">
        <footer class="mt-4">
            <p>Copyright © 2023 Sangguen,Kwon All rights reserved.</p>
            <address>Contact webmaster for more information. 010-5315-6620</address>
        </footer>
    </div>
</div>
</body>
</html>