board/urls.py
from django.urls import path
from django.views.generic import ListView

from .views import question_views, answer_views
from .models import Question


app_name = 'board'

urlpatterns = [
    path('', question_views.question_list, name='index'),

    path('question/', question_views.question_create, name='question_create'),
    path('question/<int:question_id>/', question_views.question_detail, name='question_detail'),
    path('question/<int:question_id>/delete/', question_views.question_delete, name='question_delete'),
    path('question/<int:question_id>/update/', question_views.question_update, name='question_update'),

    path('question/<int:question_id>/answer/', answer_views.answer_create, name='answer_create'),
    path('answer/<int:answer_id>/delete', answer_views.answer_delete, name='answer_delete'),
    path('answer/<int:answer_id>/update', answer_views.answer_update, name='answer_update'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
    path('accounts/', include('accounts.urls')),

]

board/models.py
from django.db import models
from django.contrib.auth.models import User


class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=100)
    contents = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    contents = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

board/forms.py
from django import forms

from .models import Question, Answer


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'contents']
        labels = {'subject': '제목', 'contents': '내용'}


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['contents']
        labels = {'contents': '내용'}

board/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DeleteView
from .models import Question, Answer
from .forms import QuestionForm, AnswerForm


question_list = ListView.as_view(model=Question, ordering=['-created_at'])


def question_detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'board/question_detail.html', {'question': question})


@login_required
def question_create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.save()
            messages.success(request, '질문이 등록되었습니다.')
            return redirect('board:index')
    else:
        form = QuestionForm()
    return render(request, 'board/question_create.html', {'form': form})


@login_required
def question_delete(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == 'POST':
        if request.user != question.author:
            messages.error(request, '현재 게시물에 대한 삭제 권한이 없습니다.')
            return redirect('board:question_detail', question_id=question_id)
        question.delete()
        messages.success(request, '질문을 삭제하였습니다.')
    return redirect('board:index')


@login_required
def question_update(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == 'POST':
        if request.user != question.author:
            messages.error(request, '현재 게시물에 대한 수정 권한이 없습니다.')
            return redirect('board:question_detail', question_id=question_id)
        form = QuestionForm(request.POST, instance=question)
        form.save()
        messages.success(request, '질문을 수정하였습니다.')
        return redirect('board:question_detail', question_id=question_id)
    else:
        form = QuestionForm(instance=question)
    return render(request, 'board/question_update.html', {'form': form})


@login_required
def answer_create(request, question_id):
    if request.method == 'POST':
        question = get_object_or_404(Question, pk=question_id)
        answer = Answer(question=question, author=request.user, contents=request.POST['contents'])
        answer.save()
        messages.success(request, '답변을 등록하였습니다.')
    return redirect('board:question_detail', question_id=question_id)


@login_required
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    question_id = answer.question_id
    if request.method == 'POST':
        if request.user != answer.author:
            messages.error(request, '현재 게시물에 대한 삭제 권한이 없습니다.')
            return redirect('board:question_detail', question_id=question_id)
        answer.delete()
        messages.success(request, '답변을 삭제하였습니다.')
    return redirect('board:question_detail', question_id=question_id)


@login_required
def answer_update(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    question_id = answer.question_id
    if request.method == 'POST':
        if request.user != answer.author:
            messages.error(request, '현재 게시물에 대한 수정 권한이 없습니다.')
            return redirect('board:question_detail', question_id=question_id)
        form = AnswerForm(request.POST, instance=answer)
        form.save()
        messages.success(request, '답변을 수정하였습니다.')
        return redirect('board:question_detail', question_id=question_id)
    else:
        form = AnswerForm(instance=answer)
    return render(request, 'board/answer_update.html', {'form': form})

board/views/answer_views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from board.models import Question, Answer
from board.forms import AnswerForm


@login_required
def answer_create(request, question_id):
    if request.method == 'POST':
        question = get_object_or_404(Question, pk=question_id)
        answer = Answer(question=question, author=request.user, contents=request.POST['contents'])
        answer.save()
        messages.success(request, '답변을 등록하였습니다.')
    return redirect('board:question_detail', question_id=question_id)


@login_required
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    question_id = answer.question_id
    if request.method == 'POST':
        if request.user != answer.author:
            messages.error(request, '현재 게시물에 대한 삭제 권한이 없습니다.')
            return redirect('board:question_detail', question_id=question_id)
        answer.delete()
        messages.success(request, '답변을 삭제하였습니다.')
    return redirect('board:question_detail', question_id=question_id)


@login_required
def answer_update(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    question_id = answer.question_id
    if request.method == 'POST':
        if request.user != answer.author:
            messages.error(request, '현재 게시물에 대한 수정 권한이 없습니다.')
            return redirect('board:question_detail', question_id=question_id)
        form = AnswerForm(request.POST, instance=answer)
        form.save()
        messages.success(request, '답변을 수정하였습니다.')
        return redirect('board:question_detail', question_id=question_id)
    else:
        form = AnswerForm(instance=answer)
    return render(request, 'board/answer_update.html', {'form': form})

board/views/question_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator

from board.models import Question
from board.forms import QuestionForm
from board.utils import set_page_bar_range


def question_list(request):
    question_list = Question.objects.all().order_by('-created_at')
    page_number = request.GET.get('page', default=1)
    paginator = Paginator(question_list, 15)
    page_obj = paginator.page(page_number)
    page_bar_range = set_page_bar_range(page_object=page_obj, bar_range=5)
    context = {'question_list': page_obj, 'page_bar_range': page_bar_range}
    return render(request, 'board/question_list.html', context)


def question_detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'board/question_detail.html', {'question': question})


@login_required
def question_create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.save()
            messages.success(request, '질문이 등록되었습니다.')
            return redirect('board:index')
    else:
        form = QuestionForm()
    return render(request, 'board/question_create.html', {'form': form})


@login_required
def question_delete(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == 'POST':
        if request.user != question.author:
            messages.error(request, '현재 게시물에 대한 삭제 권한이 없습니다.')
            return redirect('board:question_detail', question_id=question_id)
        question.delete()
        messages.success(request, '질문을 삭제하였습니다.')
    return redirect('board:index')


@login_required
def question_update(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == 'POST':
        if request.user != question.author:
            messages.error(request, '현재 게시물에 대한 수정 권한이 없습니다.')
            return redirect('board:question_detail', question_id=question_id)
        form = QuestionForm(request.POST, instance=question)
        form.save()
        messages.success(request, '질문을 수정하였습니다.')
        return redirect('board:question_detail', question_id=question_id)
    else:
        form = QuestionForm(instance=question)
    return render(request, 'board/question_update.html', {'form': form})

templates/board/answer_update.html
{% extends 'layout.html' %}

{% block content %}
    {% url 'board:answer_update' question.id answer.id as answer_update_url %}
    {% include 'board/snippets/base_form.html' with link=answer_update_url form_title='답변 수정' %}
{% endblock %}

templates/board/question_create.html
{% extends 'layout.html' %}

{% block content %}
    {% url 'board:question_create' question_id as question_create_url %}
    {% include 'board/snippets/base_form.html' with link=question_create_url form_title='질문 등록'%}
{% endblock %}

templates/board/question_detail.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div class="d-flex justify-content-center">
            <div class="col-sm-8">
                <!-- Question Title -->
                <div class="mb-3">
                    <h3><span class="badge bg-info"> Q </span></h3>
                    <h3>{{ question.subject }}</h3>
                    <div class="float-end">
                        {% if request.user == question.author %}
                            <a class="btn btn-outline-success btn-sm" href="{% url 'board:question_update' question.id %}" role="button">수정</a>
                            {% url 'board:question_delete' question.id as question_delete_url %}
                            {% include 'board/snippets/delete_modal.html' with link=question_delete_url modal_name='question_delete'%}
                        {% endif %}
                    </div>
                </div>
                <!-- Question Contents -->
                <div>
                    <span class="badge bg-secondary">{{ question.author }}</span>
                    <div class="card card-body">
                        {{ question.contents|linebreaksbr }}
                    </div>
                </div>

                <!-- Answer Title -->
                <div class="mt-5">
                    <h3><span class="badge bg-success">A</span></h3>
                    <label for="exampleFormControlTextarea1" class="form-label">
                        총 {{ question.answer_set.count }} 개의 답변이 있습니다.
                    </label>
                </div>
                <!-- Answer Contents List -->
                {% for answer in question.answer_set.all %}
                    <div class="mt-3 mb-2">
                        <span class="badge bg-secondary">{{ answer.author }}</span>
                        <div class="float-end">
                            {% if request.user == answer.author %}
                                <a class="btn btn-outline-success btn-sm" href="{% url 'board:answer_update' answer.id %}" role="button">수정</a>
                                {% url 'board:answer_delete' answer.id as answer_delete_url %}
                                {% include 'board/snippets/delete_modal.html' with link=answer_delete_url modal_name='answer_delete' %}
                            {% endif %}
                        </div>
                    </div>
                    <div class="card card-body">
                        {{ answer.contents|linebreaksbr }}
                    </div>
                {% endfor %}

                <!-- Answer Write Area -->
                <hr>
                <div class="mt-3">
                    <form action="{% url 'board:answer_create' question.id %}" method="POST">
                        {% csrf_token %}
                        <textarea class="form-control" id="exampleFormControlTextarea1" rows="10" name="contents"
                                  placeholder="답변 내용 작성"></textarea>
                        <input class="btn btn-outline-primary mt-4 float-end" type="submit" value="답변 등록">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/board/question_list.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">

        <div class="d-flex justify-content-center">
            <div class="col-sm-10">
                <a href="{% url 'board:question_create' %}" class="btn btn-dark float-end" role="button">질문등록</a>
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col" style="width: 5%;">#</th>
                        <th scope="col" style="width: 50%;">제목</th>
                        <th scope="col" style="width: 20%;">작성자</th>
                        <th scope="col" style="width: 25%;">작성일시</th>
                    </tr>
                    </thead>
                    <tbody class="table-group-divider">
                    {% for question in question_list %}
                        <tr>
                            <th scope="row">{{ question.id }}</th>
                            <td>
                                <a href="{% url 'board:question_detail' question.id %}"
                                   style="text-decoration: none;">{{ question.subject }}</a>
                                <span class="badge rounded-pill text-bg-light">{{ question.answer_set.count }}</span>
                            </td>
                            <td>{{ question.author }}</td>
                            <td>{{ question.created_at }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

        <div class="d-flex justify-content-center mt-4">
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    <!-- 첫 페이지 이동 -->
                    <li class="page-item">
                        <a class="page-link" href="?page=1" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                    <!-- 이전 페이지 이동 -->
                    <li class="page-item">
                        {% if question_list.has_previous %}
                            <a class="page-link" href="?page={{ question_list.previous_page_number }}" aria-label="Previous"><span aria-hidden="true">Previous</span></a>
                        {% endif %}
                    </li>

                    <!-- 페이지 이동 -->
                    {% for page_number in page_bar_range %}
                        {% if question_list.number == page_number %}
                            <li class="page-item active"><a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a></li>
                        {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a></li>
                        {% endif %}
                    {% endfor %}

                    <!-- 다음 페이지 이동 -->
                    <li class="page-item">
                        {% if question_list.has_next %}
                        <a class="page-link" href="?page={{ question_list.next_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">Next</span>
                        </a>
                        {% endif %}
                    </li>

                    <!-- 마지막 페이지 이동 -->
                    <li class="page-item">
                        <a class="page-link" href="?page={{ question_list.paginator.num_pages }}"
                           aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
{% endblock %}

templates/board/question_update.html
{% extends 'layout.html' %}

{% block content %}
    {% url 'board:question_update' question_id as question_update_url %}
    {% include 'board/snippets/base_form.html' with link=question_update_url form_title='질문 수정' %}
{% endblock %}